name: Execute a webhook

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'  # Every midnight KST

jobs:
  webhook:
    name: Execute a webhook
    runs-on: ubuntu-latest
    steps:
      - name: Execute a webhook
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |-
            원스토어 출석 체크 해슴 안해슴?
